[platformio]
default_envs = pico2

[env:pico2]
; Arduino-Pico integration with verified RP2350 / Pico 2 board support.
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#5d4561a05e3b212660ac6fdd3fbfb328d1988aa1
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags = -DAAC_DISPLAY_BACKEND_PD2200
